name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup MoonBit
        uses: moonbitlang/setup-moonbit@v1
      - name: Check
        run: moon check --all
      - name: Test
        run: moon test
      - name: Build
        run: moon build --release